# Generated by Django 3.0.8 on 2020-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdetails',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
